"""empty message

Revision ID: 295fbb633167
Revises: 8bf423cdff5f
Create Date: 2024-07-23 12:17:23.061378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '295fbb633167'
down_revision = '8bf423cdff5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite')
    op.drop_table('user')
    op.drop_table('character')
    op.drop_table('planet')
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('planet_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('terrain', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('key_event', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='planet_pkey'),
    sa.UniqueConstraint('name', name='planet_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('character',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('character_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('faction', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('race', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('homeworld_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['homeworld_id'], ['planet.id'], name='character_homeworld_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='character_pkey'),
    sa.UniqueConstraint('name', name='character_name_key'),
    postgresql_ignore_search_path=False
    )
 
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.create_table('favorite',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], name='favorite_character_id_fkey'),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], name='favorite_planet_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorite_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='favorite_pkey')
    )
    # ### end Alembic commands ###
